import type { TextChunk } from './pdf'

export type ReaderState =
  | 'idle'
  | 'loading-model'
  | 'ready'
  | 'buffering'
  | 'playing'
  | 'paused'

// A few good Kokoro voices to offer in the UI.
export const VOICES = [
  { id: 'af_heart', label: 'Heart (US, warm)' },
  { id: 'af_bella', label: 'Bella (US)' },
  { id: 'am_michael', label: 'Michael (US, male)' },
  { id: 'bf_emma', label: 'Emma (UK)' },
  { id: 'bm_george', label: 'George (UK, male)' },
]

// Make PDF-extracted text nicer to listen to: re-join hyphenated line breaks
// and drop bracketed citation markers like [12] that sound awful spoken.
export function speakable(text: string): string {
  return text
    .replace(/(\w)- (\w)/g, '$1$2')
    .replace(/\s*\[[\d,\s–-]+\]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
}

// Drives read-aloud playback. Speech is generated by Kokoro in a Web Worker
// (see tts.worker.ts) so the page never freezes; this class queues requests,
// plays chunks in order, and pre-generates the next chunk for smooth playback.
export class KokoroReader {
  private worker: Worker | null = null
  private pending = new Map<number, { resolve: (b: Blob) => void; reject: (e: Error) => void }>()
  private nextId = 1

  private chunks: TextChunk[] = []
  private audio = new Audio()
  private cache = new Map<string, string>() // `${voice}:${index}` -> blob URL
  private wantPlaying = false
  private currentIndex = 0
  // Bumped on every play/seek/pause; async work checks it so a stale
  // generation can't hijack playback after the user has jumped elsewhere.
  private epoch = 0
  // In-flight model load, shared by concurrent loadModel() callers.
  private loading: Promise<void> | null = null

  voice = 'af_heart'
  speed = 1.1
  state: ReaderState = 'idle'
  // Which engine the voice runs on: 'webgpu' (fast) or 'wasm' (compatibility
  // fallback, e.g. Safari 18 — noticeably slower per sentence).
  device: 'webgpu' | 'wasm' | null = null

  onIndexChange?: (index: number) => void
  onStateChange?: (state: ReaderState) => void
  // Shown on the phone's lock screen while reading.
  title = 'Scribe'

  constructor() {
    this.audio.addEventListener('ended', () => this.handleEnded())
    // Keep playing inside the page on iOS (no fullscreen video takeover),
    // and keep the audio session alive for background/lock-screen playback.
    ;(this.audio as HTMLAudioElement & { playsInline?: boolean }).playsInline = true
    this.audio.setAttribute('playsinline', '')
    this.wireMediaSession()
  }

  // Lock-screen / control-center transport controls (iPhone background play).
  private wireMediaSession() {
    if (!('mediaSession' in navigator)) return
    const ms = navigator.mediaSession
    ms.setActionHandler?.('play', () => this.play())
    ms.setActionHandler?.('pause', () => this.pause())
    ms.setActionHandler?.('previoustrack', () => this.seekTo(this.currentIndex - 1))
    ms.setActionHandler?.('nexttrack', () => this.seekTo(this.currentIndex + 1))
  }

  private updateMediaSession() {
    if (!('mediaSession' in navigator)) return
    navigator.mediaSession.metadata = new MediaMetadata({
      title: this.title,
      artist: 'Scribe',
    })
    navigator.mediaSession.playbackState =
      this.state === 'playing' || this.state === 'buffering' ? 'playing' : 'paused'
  }

  private setState(s: ReaderState) {
    this.state = s
    this.onStateChange?.(s)
    this.updateMediaSession()
  }

  get index() {
    return this.currentIndex
  }

  get modelLoaded() {
    return this.worker !== null && this.state !== 'idle' && this.state !== 'loading-model'
  }

  listVoices(): { id: string; label: string }[] {
    return VOICES.map((v) => ({ id: v.id, label: v.label }))
  }

  // Changing voice or speed invalidates everything already generated (the
  // cache is keyed by voice only, and speed is baked into the audio).
  setVoice(v: string) {
    if (this.voice === v) return
    this.voice = v
    this.clearCache()
  }

  setSpeed(s: number) {
    if (this.speed === s) return
    this.speed = s
    this.clearCache()
  }

  // Idempotent: concurrent callers all await the same in-flight load, so
  // preloading at startup can't leave a later caller thinking it's ready.
  async loadModel(onProgress?: (pct: number) => void): Promise<void> {
    if (this.modelLoaded) return
    if (this.loading) return this.loading
    this.loading = this.doLoad(onProgress)
    try {
      await this.loading
    } finally {
      this.loading = null
    }
  }

  private async doLoad(onProgress?: (pct: number) => void) {
    this.setState('loading-model')
    const worker = new Worker(new URL('./tts.worker.ts', import.meta.url), { type: 'module' })
    this.worker = worker
    try {
      await new Promise<void>((resolve, reject) => {
        worker.onmessage = (e) => {
          const m = e.data
          if (m.type === 'progress') onProgress?.(m.progress)
          else if (m.type === 'loaded') {
            this.device = m.device ?? null
            resolve()
          } else if (m.type === 'error') reject(new Error(m.error))
        }
        worker.onerror = (e) => reject(new Error(e.message || 'worker failed'))
        worker.postMessage({ type: 'load' })
      })
    } catch (e) {
      worker.terminate()
      this.worker = null
      this.setState('idle')
      throw e
    }
    // Steady-state message handling for generation results.
    worker.onmessage = (e) => {
      const m = e.data
      if (m.type === 'audio') {
        this.pending.get(m.id)?.resolve(m.blob)
        this.pending.delete(m.id)
      } else if (m.type === 'error') {
        if (m.id != null) {
          this.pending.get(m.id)?.reject(new Error(m.error))
          this.pending.delete(m.id)
        } else {
          console.error('tts worker error', m.error)
        }
      }
    }
    this.setState('ready')
  }

  private generateBlob(text: string): Promise<Blob> {
    const id = this.nextId++
    return new Promise((resolve, reject) => {
      if (!this.worker) return reject(new Error('model not loaded'))
      this.pending.set(id, { resolve, reject })
      this.worker.postMessage({
        type: 'generate',
        id,
        text,
        voice: this.voice,
        speed: this.speed,
      })
    })
  }

  setChunks(chunks: TextChunk[]) {
    this.chunks = chunks
    this.currentIndex = 0
    this.clearCache()
  }

  private clearCache() {
    for (const url of this.cache.values()) URL.revokeObjectURL(url)
    this.cache.clear()
    this.queue = []
  }

  // ---- Generation scheduling ----
  // One generation runs at a time; `queue` holds chunk indices in priority
  // order. A tapped/playing chunk goes to the FRONT so it never waits behind
  // prefetch work (crucial on the slow WASM engine where each generation can
  // take seconds).
  private queue: number[] = []
  private generating = false
  private waiters = new Map<string, { resolve: (u: string) => void; reject: (e: unknown) => void }[]>()

  private keyFor(index: number) {
    return `${this.voice}:${index}`
  }

  private audioUrlFor(index: number, urgent = false): Promise<string> {
    const key = this.keyFor(index)
    const hit = this.cache.get(key)
    if (hit) return Promise.resolve(hit)
    const promise = new Promise<string>((resolve, reject) => {
      const list = this.waiters.get(key) ?? []
      list.push({ resolve, reject })
      this.waiters.set(key, list)
    })
    this.queue = this.queue.filter((i) => i !== index)
    if (urgent) this.queue.unshift(index)
    else this.queue.push(index)
    this.pump()
    return promise
  }

  private async pump() {
    if (this.generating) return
    this.queue = this.queue.filter((i) => !this.cache.has(this.keyFor(i)))
    const index = this.queue.shift()
    if (index === undefined) return
    const key = this.keyFor(index)
    this.generating = true
    try {
      const text = speakable(this.chunks[index].text)
      const blob = await this.generateBlob(text || '.')
      const url = URL.createObjectURL(blob)
      this.cache.set(key, url)
      this.waiters.get(key)?.forEach((w) => w.resolve(url))
    } catch (e) {
      this.waiters.get(key)?.forEach((w) => w.reject(e))
    } finally {
      this.waiters.delete(key)
      this.generating = false
      this.pump()
    }
  }

  // Generate upcoming chunks ahead of time so there's no gap between
  // sentences. On the slow WASM engine, keep a deep rolling buffer working
  // ahead so continuous listening stays smooth and nearby taps get instant;
  // the priority queue ensures a tap never waits behind this buffer.
  private prefetchNext() {
    const depth = this.device === 'wasm' ? 20 : 2
    for (let i = 1; i <= depth; i++) {
      const next = this.currentIndex + i
      if (next < this.chunks.length) {
        this.audioUrlFor(next).catch(() => {})
      }
    }
    // Bound memory: drop generated audio far behind/ahead of the listener.
    for (const [key, url] of this.cache) {
      const idx = Number(key.split(':').pop())
      if (idx < this.currentIndex - 25 || idx > this.currentIndex + 60) {
        URL.revokeObjectURL(url)
        this.cache.delete(key)
      }
    }
  }

  async play() {
    if (!this.chunks.length) return
    this.wantPlaying = true
    await this.playIndex(this.currentIndex)
  }

  private async playIndex(index: number) {
    const myEpoch = ++this.epoch
    if (index >= this.chunks.length) {
      this.wantPlaying = false
      this.setState('ready')
      return
    }
    this.currentIndex = index
    this.onIndexChange?.(index)
    this.setState('buffering')
    let url: string
    try {
      url = await this.audioUrlFor(index, true)
    } catch (e) {
      console.error('tts generation failed', e)
      if (myEpoch === this.epoch) this.setState('paused')
      return
    }
    // A newer play/seek/pause superseded this request while we were
    // generating — let that one drive playback.
    if (myEpoch !== this.epoch || !this.wantPlaying) return
    this.audio.src = url
    try {
      await this.audio.play()
    } catch (e) {
      // Browser blocked playback (e.g. the "user gesture" window expired while
      // the model was still downloading). Stay paused; the next tap resumes.
      console.warn('audio playback blocked', e)
      this.wantPlaying = false
      this.setState('paused')
      return
    }
    this.setState('playing')
    this.prefetchNext()
  }

  private handleEnded() {
    if (!this.wantPlaying) return
    this.playIndex(this.currentIndex + 1)
  }

  pause() {
    this.epoch++
    this.wantPlaying = false
    this.audio.pause()
    this.setState('paused')
  }

  async toggle() {
    if (this.state === 'playing' || this.state === 'buffering') this.pause()
    else await this.play()
  }

  // Jump to a chunk (e.g. the user tapped a sentence). Resumes playing if we
  // were already playing.
  async seekTo(index: number) {
    const wasPlaying = this.wantPlaying
    this.epoch++
    this.audio.pause()
    this.currentIndex = Math.max(0, Math.min(index, this.chunks.length - 1))
    this.onIndexChange?.(this.currentIndex)
    if (wasPlaying) {
      this.wantPlaying = true
      await this.playIndex(this.currentIndex)
    } else this.setState('paused')
  }

  dispose() {
    this.audio.pause()
    this.worker?.terminate()
    this.worker = null
    this.clearCache()
  }
}
